on:
  push:

defaults:
  run:
    shell: sh

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v2
      - name: prepare
        run: apk add build-base perl-utils
      - name: make all
        run: make all
      - name: hax
        run: |
          ( trap - PIPE; yes; ) | ./xe -a -s "sed q" -- 1 2 3
      - name: make check
        run: make check

