on:
  push:

defaults:
  run:
    shell: sh

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: alpine:latest
    steps:
      - uses: actions/checkout@v2
      - name: prepare
        run: apk add build-base perl-utils
      - name: make all
        run: make all
      - name: make check
        run: make check
      - name: bors
        run: |
          env